config/routes.rb
Rails.application.routes.draw do
  get 'spot_comments/show'
  get 'spot_comments/new'
  get 'spot_comments/create'
  get 'spot_comments/update'
  get 'spot_comments/destroy'
  get '/admin' => 'spots#index', as: 'admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :spots

  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
    get '/users/:id' => 'users/registrations#show', as: 'user'
    get '/users' => 'users#index', as: 'users_index'
    delete '/users/:id' => 'users#destroy'
  end

  namespace :api, {format: 'json'} do
    resources :spots do
      resources :likes, only: %i[create destroy]
    end
    get '/excite-places' => 'spots#index_only_excite_places'
    get '/current_user' => 'users#show_current_user'
    resources :spot_comments
    resources :api_docs, only: [:index]
    resources :users, only: %i[index show update]
    get '/user_spots_count_each_mood/:id' => 'users#user_spots_count_each_mood'
    get '/users/:id/profile-image' => 'users#show_profile_image'
    put '/users/:id/profile-image' => 'users#update_profile_image'
    get '/users/:id/likes' => 'users#likes'
    get '/users/:id/like/:spot_id' => 'users#already_liked?'
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, via: %i[get post]
    end
  end

  root 'static_pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>
    </head>

  <body>
    <header>
      <nav>
        <%= link_to 'ホーム', admin_path %> 
          <% if user_signed_in? %>
            <%= link_to 'ユーザー一覧', users_index_path %> 
            <%= link_to 'エキサイトプレイス追加', new_spot_path %> 
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'サインアップ', new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
          <% end %>
      </nav>
    </header>
    <h1>ExciteMap管理者専用ページ</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>